install.packages("rjson")
install.packages("lme4", dependencies = TRUE)
install.packages("survival", dependencies = TRUE)
install.packages("coxme", dependencies = TRUE)
install.packages("lmerTest", dependencies = TRUE)
install.packages("bbmle", dependencies = TRUE)
install.packages("survminer", dependencies = TRUE)
install.packages("rcompanion", dependencies = TRUE)